#!/usr/bin/env bash
# refine.sh — Second layer: Gemini audio-aware subtitle refinement
# Usage: refine.sh <audio-file> <srt-file> [options]
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  refine.sh <audio-file> <srt-file> [options]

Options:
  --model MODEL           Gemini model (default: gemini-2.5-flash)
  --mode MODE             Language behavior (default: preserve)
                            preserve         keep all original languages as spoken
                            <lang>           translate everything (e.g. zh, en, ja, ko)
                            bilingual-<lang> original + translation (e.g. bilingual-zh)
  --out PATH              Output SRT (default: <srt>.refined.srt)
  --api-key KEY           Gemini API key (or set GEMINI_API_KEY env)
EOF
  exit 2
}

[[ "${1:-}" == "" || "${1:-}" == "-h" || "${1:-}" == "--help" ]] && usage

audio="$1"; shift
srt_in="$1"; shift

model="gemini-3-flash-preview"
lang_mode="preserve"
out=""
api_key="${GEMINI_API_KEY:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model)   model="${2:-}";    shift 2 ;;
    --mode)    lang_mode="${2:-}"; shift 2 ;;
    --out)     out="${2:-}";      shift 2 ;;
    --api-key) api_key="${2:-}";  shift 2 ;;
    *) echo "Unknown arg: $1" >&2; usage ;;
  esac
done

[[ ! -f "$audio" ]] && { echo "[refine] Audio file not found: $audio" >&2; exit 1; }
[[ ! -f "$srt_in" ]] && { echo "[refine] SRT file not found: $srt_in" >&2; exit 1; }
[[ -z "$api_key" ]] && { echo "[refine] Missing GEMINI_API_KEY or --api-key" >&2; exit 1; }

# Default output path
if [[ -z "$out" ]]; then
  base="${srt_in%.srt}"
  out="${base}.refined.srt"
fi
mkdir -p "$(dirname "$out")"

# ─── Detect MIME type ───
mime_type=$(file --mime-type -b "$audio")
file_size=$(wc -c < "$audio" | tr -d ' ')

echo "[refine] Uploading audio to Gemini Files API..." >&2

# ─── Step 1: Start resumable upload ───
upload_url=$(curl -sS -X POST \
  "https://generativelanguage.googleapis.com/upload/v1beta/files?key=${api_key}" \
  -H "X-Goog-Upload-Protocol: resumable" \
  -H "X-Goog-Upload-Command: start" \
  -H "X-Goog-Upload-Header-Content-Length: ${file_size}" \
  -H "X-Goog-Upload-Header-Content-Type: ${mime_type}" \
  -H "Content-Type: application/json" \
  -d '{"file": {"display_name": "audio_for_refinement"}}' \
  -D - 2>/dev/null \
  | grep -i "x-goog-upload-url:" | tr -d '\r' | awk '{print $2}')

[[ -z "$upload_url" ]] && { echo "[refine] Failed to get upload URL" >&2; exit 1; }

# ─── Step 2: Upload file bytes ───
file_uri=$(curl -sS -X PUT "$upload_url" \
  -H "Content-Length: ${file_size}" \
  -H "X-Goog-Upload-Offset: 0" \
  -H "X-Goog-Upload-Command: upload, finalize" \
  -H "Content-Type: ${mime_type}" \
  --data-binary "@${audio}" \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['file']['uri'])")

[[ -z "$file_uri" ]] && { echo "[refine] Failed to upload audio" >&2; exit 1; }

echo "[refine] Uploaded: ${file_uri}" >&2

# ─── Step 3: Build language instruction ───
case "$lang_mode" in
  preserve)
    lang_instruction="Preserve whatever language(s) the speaker actually used. If they spoke Chinese, keep Chinese. If English, keep English. If mixed (code-switching), preserve the mix exactly as spoken. Do NOT translate or normalize to any single language."
    ;;
  bilingual-*)
    target_lang="${lang_mode#bilingual-}"
    lang_instruction="Output bilingual subtitles: keep the original spoken language on the first line, then add a translation into '${target_lang}' on the next line, both within the same subtitle block."
    ;;
  *)
    lang_instruction="Translate all subtitle content into '${lang_mode}'. Output only in '${lang_mode}'."
    ;;
esac

# ─── Step 4: Build prompt ───
srt_content=$(cat "$srt_in")

prompt="You are a professional subtitle proofreader with expertise in multilingual content.

You have been given:
1. An audio file (attached)
2. A draft SRT subtitle file generated by an ASR model (Whisper)

Your task is to proofread and correct the subtitles by listening to the audio and comparing it with the draft.

STRICT RULES:
- Keep existing timestamps as accurate as possible. Only adjust if clearly wrong.
- Correct any transcription errors you hear (wrong words, wrong language detection).
- If you hear spoken content in the audio that is MISSING from the draft SRT, ADD new subtitle blocks with appropriate timestamps.
- ${lang_instruction}
- Output ONLY valid SRT format — no explanations, no markdown code blocks, no extra text.
- Re-number subtitle blocks sequentially after any additions.

DRAFT SRT:
${srt_content}"

prompt_json=$(python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" <<< "$prompt")

# ─── Step 5: Call Gemini generateContent with fallback chain ───
# HARD RULE: Do NOT add max_output_tokens. Let the model use its full capacity.
# Fallback chain: try models in order, skip to next on error.
FALLBACK_MODELS=(
  "$model"
  "gemini-2.5-flash"
  "gemini-2.5-pro"
  "gemini-3.1-pro-preview"
  "gemini-3-pro-preview"
)

# Deduplicate (if user-specified model is already in the list)
seen=()
UNIQUE_MODELS=()
for m in "${FALLBACK_MODELS[@]}"; do
  skip=false
  for s in "${seen[@]:-}"; do [[ "$s" == "$m" ]] && skip=true; done
  if ! $skip; then
    seen+=("$m")
    UNIQUE_MODELS+=("$m")
  fi
done

response=""
used_model=""
for try_model in "${UNIQUE_MODELS[@]}"; do
  echo "[refine] Trying Gemini ${try_model}..." >&2
  response=$(curl -sS \
    "https://generativelanguage.googleapis.com/v1beta/models/${try_model}:generateContent?key=${api_key}" \
    -H "Content-Type: application/json" \
    -d "{
      \"contents\": [{
        \"parts\": [
          {\"file_data\": {\"mime_type\": \"${mime_type}\", \"file_uri\": \"${file_uri}\"}},
          {\"text\": ${prompt_json}}
        ]
      }],
      \"generation_config\": {
        \"temperature\": 0.1
      }
    }")

  # Check if response has error
  has_error=$(echo "$response" | python3 -c "import sys,json; d=json.load(sys.stdin); print('yes' if 'error' in d else 'no')" 2>/dev/null || echo "yes")
  if [[ "$has_error" == "no" ]]; then
    used_model="$try_model"
    break
  else
    err_msg=$(echo "$response" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('error',{}).get('message','unknown')[:80])" 2>/dev/null || echo "unknown")
    echo "[refine] ${try_model} failed: ${err_msg}. Trying next..." >&2
  fi
done

if [[ -z "$used_model" ]]; then
  echo "ERROR: All models failed. Last error: ${err_msg:-unknown}" >&2
  exit 1
fi

echo "[refine] Success with ${used_model}" >&2

# ─── Step 6: Extract and clean output ───
tmp_response=$(mktemp)
echo "$response" > "$tmp_response"

result=$(python3 - "$tmp_response" <<'PYEOF'
import sys, json

with open(sys.argv[1]) as f:
    response_text = f.read()

try:
    d = json.loads(response_text)
except json.JSONDecodeError:
    print("ERROR: invalid JSON response", file=sys.stderr)
    print(response_text[:500], file=sys.stderr)
    sys.exit(1)

if 'error' in d:
    print(f"ERROR: {d['error']['message']}", file=sys.stderr)
    sys.exit(1)

if 'candidates' not in d or not d['candidates']:
    print("ERROR: no candidates in response", file=sys.stderr)
    print(json.dumps(d, indent=2), file=sys.stderr)
    sys.exit(1)

text = d['candidates'][0]['content']['parts'][0]['text'].strip()

# Strip markdown code fences if model wrapped the output
if text.startswith('```'):
    lines = text.split('\n')
    lines = [l for l in lines if not l.startswith('```')]
    text = '\n'.join(lines).strip()

print(text)
PYEOF
)
rm -f "$tmp_response"

echo "$result" > "$out"
echo "[refine] Done → ${out}" >&2
echo "$out"
